### PR TITLE
Update AndroidManifest.xml

### PR DESCRIPTION
**Pull request by TakiShiwa**
- Tried to fix weird long application name in app drawer and in notification panel

### CODE REVIEW

**Comment by 23rd** [comment]
This breaks my build.

**Comment by TakiShiwa** [comment]
Aaah I see 
Sorry about that

**Comment by TakiShiwa** [comment]
Let me re-sync and do it from the start

**Comment by TakiShiwa** [comment]
Screenshot 2023-07-27 at 22-57-23 Code search results
Screenshot 2023-07-27 at 22-57-35 Code search results


I tried to compare with the original Telegram, but it looks nothing suspicious 
maybe the sting name got interchanged somewhere with that long name string

**Comment by TakiShiwa** [comment]
Finally you fixed it @23rd , 
I want to know which string was responsible for that

**Comment by 23rd** [comment]
I did nothing. I think it is not fixed.

**Comment by TakiShiwa** [comment]
I downloaded the app that you published on GitHub 2 days ago, 
but the f-droid one is still having the same issue.

**Comment by TakiShiwa** [comment]
> I downloaded the app that you published on GitHub 2 days ago, but the f-droid one is still having the same issue.

It's just standalone, a separate app from f-droid one, I thought it would be just an update

**Pull request closed without merging**
